#pragma once

enum DataSize {
  DEPTH_WIDTH = 512,
  DEPTH_HEIGHT = 424,
  COLOR_WIDTH = 1920,
  COLOR_HEIGHT = 1080,

  DEPTH_SIZE = DEPTH_WIDTH * DEPTH_HEIGHT,
  COLOR_SIZE = DEPTH_SIZE * 3,
  COMBINED_SIZE = DEPTH_SIZE * 4,
  FRAME_SIZE = COMBINED_SIZE,
};